fineract-provider/config/swagger/fineract-input.yaml.template

Updating the list of servers in swagger for connecting to velocity servers

Swagger server list update

---

fineract-provider/src/main/resources/static/api-docs/velocity-doc.md

Api documentation

---

docker-compose-activemq.yml
fineract-provider/src/main/java/org/apache/fineract/commands/service/CommandWrapperBuilder.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/VoucherConstants.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/api/VoucherApiResource.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/data/VoucherBalanceDTO.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/data/VoucherDTO.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/domain/Voucher.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/domain/VoucherRepository.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/domain/VoucherTransaction.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/domain/VoucherTransactionRepository.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/handler/UseVoucherHandler.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/service/VoucherReadService.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/service/VoucherReadServiceImpl.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/service/VoucherWriteService.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/voucher/service/VoucherWriteServiceImpl.java
fineract-provider/src/main/resources/sql/migrations/core_db/V1000__velocity_voucher_datatable.sql
fineract-provider/src/main/resources/sql/migrations/core_db/V1001__velocity_voucher_permissions.sql
fineract-provider/src/main/resources/sql/migrations/core_db/V1002__velocity_credit_currency.sql
fineract-provider/src/main/resources/sql/migrations/core_db/V1003__velocity_chart_of_accounts_data.sql
fineract-provider/src/main/resources/sql/migrations/core_db/V1005__velocity_credits_product.sql
fineract-provider/src/main/resources/sql/migrations/core_db/V1006__velocity_remove_mobileno_unique_contraint.sql
fineract-provider/src/main/resources/sql/migrations/core_db/V1007__velocity_voucher_transactions.sql
fineract-provider/src/main/resources/sql/migrations/core_db/V1008__velocity_voucher_transactions_permissions.sql
fineract-provider/src/main/resources/static/api-docs/velocity-doc.md

This adds voucher entities and
1 - Voucher transactions
2- Voucher purchasing
3- Voucher balances
4- Vouchers expiring after provided number of days

VL-748 Voucher transaction logic

---

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccount.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountSummary.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountTransactionSummaryWrapper.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java

fixing holdamount transaction running balances and savings account available balance

Holdfunds balance cleanups

---

fineract-provider/src/main/java/org/apache/fineract/infrastructure/core/boot/WebXmlAuth0Configuration.java

VL-1967 CORS filter fix

---

fineract-provider/src/main/resources/sql/migrations/list_db/V7__add_utc_to_timezones.sql

VL-1967 Timezone migration

---

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/data/SavingsAccountTransactionDataValidator.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java

VL-2052 - saving notes and adding notes parameter for hold

VL-2052 - saving notes and adding notes parameter for hold

---

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/api/SavingsAccountsApiResource.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountReadPlatformService.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountReadPlatformServiceImpl.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/self/savings/api/SelfSavingsApiResource.java

https://velocitycareerlabs.atlassian.net/browse/VL-2051
Backend changes for Search transactions by date range, amount and description.

VL-2051 - Search transactions by date range, amount and description

---

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformService.java

fix issue for failing PR

---

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/data/SavingsAccountConstant.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsApplicationProcessWritePlatformServiceJpaRepositoryImpl.java

Savings account should be able to be auto approved & activated.
Implement feature for auto approve and activate savings account.

https://velocitycareerlabs.atlassian.net/browse/VL-2244

---

fineract-provider/src/main/java/org/apache/fineract/portfolio/client/service/ClientWritePlatformServiceJpaRepositoryImpl.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/SavingsApiConstants.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/data/SavingsAccountDataDTO.java

Savings account should be able to be auto approved & activated

---

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccount.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccountTransactionRepository.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java

https://velocitycareerlabs.atlassian.net/browse/VL-2113
If transactions available it will not allowed to change future activation date.

[Mifos] Add UI to edit the savings accounts dates

---

fineract-provider/src/main/resources/sql/migrations/core_db/V1025__update_description_for_account_transfers.sql

Migration to update description for account transfers.

Fineract Migration

---

fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/api/SavingsAccountTransactionsApiResource.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountReadPlatformServiceImpl.java

VL-2325 - Saving transactions API - search using description

VL-2325 - Saving transactions API - search using description

---

fineract-provider/src/main/java/org/apache/fineract/infrastructure/security/service/Auth0UserImportService.java

VL-1915 - Returing AuthorizationException if user doesn't have fineract role, instead of error code 500.

---

eng/environments/common.sh

bumping version to 0.10.4

---

eng/environments/common.sh

Feat VL-2403: Set Top Gear 1 image versions #2403

Feat VL-2403: Set Top Gear 1 image versions #2403

---

fineract-provider/src/main/resources/sql/migrations/core_db/V1027__add_codevalue_for_clientclosure.sql

https://velocitycareerlabs.atlassian.net/browse/VL-2449

VL-2449 - adding client closure reason as code values using migration script

---

eng/environments/common.sh

bumping version to 0.11.1

---

eng/environments/common.sh

fix: version set to 0.11.1

---

eng/environments/common.sh

bumping version to 0.11.3

---

fineract-provider/src/main/java/org/apache/fineract/portfolio/account/data/AccountTransferData.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanReadPlatformServiceImpl.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/DepositAccountReadPlatformServiceImpl.java
fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountReadPlatformServiceImpl.java

VL-2708 - GET Transactions API changes to include Account ID for transfer section

---

fineract-provider/src/main/resources/static/api-docs/velocity-doc.md

Adding documentation for GET /fineract-provider/api/v1/vouchers/{Clieni}/expiring/{days}
Adding documentation for GET /savingsaccounts/1/transactions?transfersOnly=true

VL-1409 - Updating API doc

---

fineract-provider/src/main/resources/static/api-docs/velocity-doc.md

spotlessApply

---

fineract-provider/src/main/resources/static/api-docs/velocity-doc.md

Adding missing APIs docs

---

eng/environments/common.sh

feat(common.sh): update version

---

.github/workflows/fineract-build-push.yml

Reverts velocitycareerlabs/fineract#112

Revert "fix/verupdate-wf-call"

---

.github/workflows/fineract-build-push.yml

Changes made for Deal with CI deprecation warnings

Deal with CI deprecation warnings

---

.github/workflows/fineract-build-push.yml
eng/environments/common.sh

Update workflow for migration to velocitycareerlabs

Update workflow for migration to velocitycareerlabs
